### ISSUE TITLE
Failed to install wxPython on Debian

### ISSUE THREAD

**Issue by LumaRay** [wxWidgets/Phoenix#1725]
Hello.

I am trying to install wxPython on Debian 10.4 x64, but I get errors while compiling.
I use Python 3.7.3

Before installing I do this:

```
sudo apt install python3-pip
sudo apt install linux-headers-$(uname -r)
sudo apt-get install build-essential libgtk-3-dev
```

Then I run this command:
`sudo pip3 install wxpython`
After few minutes of compilation I start to get errors with this:
```
[669/917] Compiling sip/cpp/sip_glcanvascmodule.cpp
  In file included from ../../../../sip/cpp/sip_glcanvascmodule.cpp:10:
  ../../../../sip/cpp/sipAPI_glcanvas.h:682:23: error: aggregate ‘wxGLAttributes _NullGLAttributes’ has incomplete type and cannot be defined
   static wxGLAttributes _NullGLAttributes;
                         ^~~~~~~~~~~~~~~~~
  ../../../../sip/cpp/sipAPI_glcanvas.h:683:25: error: aggregate ‘wxGLContextAttrs _NULLGLContextAttrs’ has incomplete type and cannot be defined
   static wxGLContextAttrs _NULLGLContextAttrs;
                           ^~~~~~~~~~~~~~~~~~~
  In file included from ../../../../sip/cpp/sip_glcanvascmodule.cpp:10:
  ../../../../sip/cpp/sipAPI_glcanvas.h:865:198: error: ‘wxGLCanvasName’ was not declared in this scope
       wxGLCanvas(wxWindow *parent, const wxGLAttributes &dispAttrs, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=
```
I have tried many fresh Debian installs with different desktops, but it doesn't help.

I thought of opening this as an issue on wxWidgets GitHub page, but I could not find Issues section there.

**Comment by LumaRay** [comment]
Here are the last lines of the compilation output:
[wxPython-install.txt](https://github.com/wxWidgets/Phoenix/files/4917047/wxPython-install.txt)

**Comment by swt2c** [comment]
You need to install the OpenGL development packages and restart the whole process.  On Debian, these are `libgl1-mesa-dev` and `libglu1-mesa-dev`.

BTW, Debian has a wxPython package that you can install without having to compile anything, `python3-wxgtk4.0`.  It is version 4.0.x though.

**Comment by swt2c** [comment]
Another option, if you want to avoid compiling wxPython and wxWidgets, but also want wxPython 4.1.0, you can use the wheels provided here (Debian 10 is included):
https://extras.wxpython.org/wxPython4/extras/

**Comment by LumaRay** [comment]
The problem is, I need that PropertyGrid enum serialization to work properly, and it only works in 4.1.1a1: https://github.com/wxWidgets/Phoenix/issues/1714
I have compiled using libgl1-mesa-dev and libglu1-mesa-dev, but got 4.1.0... How do I get 4.1.1a1 on Debian?

**Comment by swt2c** [comment]
Ah right.  :-)  Well, installing from pip won't help you with that either.  Unfortunately, Robin doesn't seem to be building wheels for snapshot builds for Linux.  To get 4.1.1a1, you are going to have to build from source, either from GitHub checkout, or from a snapshot tarball:
https://wxpython.org/Phoenix/snapshot-builds/

Building from source is kind of complicated unfortunately.  There are some instructions here:
https://github.com/wxWidgets/Phoenix

**Comment by LumaRay** [comment]
Thank you @swt2c 
I cannot see any linux snapshots following your link. linux folder is empty there.
Meanwhile I have managed to run my program on Debian with 4.1.0 wxPython and it doesn't have that problem with enums. And as this is older version, it does show description text in propertygrid... Although it show errors like this if I add `wx.propgrid.PG_DESCRIPTION` to the style :
`Gtk-CRITICAL **: 21:55:15.001: gtk_widget_set_size_request: assertion 'width >= -1' failed`
And also as I select different properties, it shows this:
`Gtk-WARNING **: 21:55:33.927: for_size smaller than min-size (23 < 30) while measuring gadget (node entry, owner GtkSpinButton)`

**Comment by swt2c** [comment]
Yes, that's what I was saying - Robin isn't building any wheels for Linux snapshots.  You have to build from source.

GTK is unfortunately rather noisy.  Sometimes it issues warnings that are not all that helpful.  If you don't observe any actual problems while using the UI, I would just ignore them.

**Comment by LumaRay** [comment]
Allright, thank you again Scott, those libgl1-mesa-dev and libglu1-mesa-dev really helped me. Have a great day!
