### ISSUE TITLE
Please support the current version of WebKitGTK+ on Linux

### ISSUE THREAD

**Issue by haozhangphd** [wxWidgets/Phoenix#430]
I tried to compile wxPython Phoenix with WebKitGTK+ 2.16.5 (AKA webkit2gtk on some distros) , however the compilation was not successful due to the following error message:
```
[626/861] cxx: sip/cpp/sip_html2wxWebViewArchiveHandler.cpp -> build/waf/3.6/sip/cpp/sip_html2wxWebViewArchiveHandler.cpp.17.o
../../../sip/cpp/sip_html2wxWebViewArchiveHandler.cpp:18:1: error: expected class-name before ‘{’ token
 {
 ^
../../../sip/cpp/sip_html2wxWebViewArchiveHandler.cpp:21:41: error: ‘wxWebViewArchiveHandler’ in namespace ‘::’ does not name a type
     sipwxWebViewArchiveHandler(const  ::wxWebViewArchiveHandler&);
                                         ^~~~~~~~~~~~~~~~~~~~~~~
../../../sip/cpp/sip_html2wxWebViewArchiveHandler.cpp: In constructor ‘sipwxWebViewArchiveHandler::sipwxWebViewArchiveHandler(const wxString&)’:
../../../sip/cpp/sip_html2wxWebViewArchiveHandler.cpp:42:110: error: expected class-name before ‘(’ token
 sipwxWebViewArchiveHandler::sipwxWebViewArchiveHandler(const  ::wxString& scheme):  ::wxWebViewArchiveHandler(scheme), sipPySelf(0)
                                                                                                              ^
../../../sip/cpp/sip_html2wxWebViewArchiveHandler.cpp:42:110: error: expected ‘{’ before ‘(’ token
../../../sip/cpp/sip_html2wxWebViewArchiveHandler.cpp: At global scope:
../../../sip/cpp/sip_html2wxWebViewArchiveHandler.cpp:42:118: error: expected constructor, destructor, or type conversion before ‘,’ token
 sipwxWebViewArchiveHandler::sipwxWebViewArchiveHandler(const  ::wxString& scheme):  ::wxWebViewArchiveHandler(scheme), sipPySelf(0)
                                                                                                                      ^
../../../sip/cpp/sip_html2wxWebViewArchiveHandler.cpp:42:129: error: expected constructor, destructor, or type conversion before ‘(’ token
 sipwxWebViewArchiveHandler::sipwxWebViewArchiveHandler(const  ::wxString& scheme):  ::wxWebViewArchiveHandler(scheme), sipPySelf(0)
                                                                                                                                 ^
../../../sip/cpp/sip_html2wxWebViewArchiveHandler.cpp:47:65: error: ‘wxWebViewArchiveHandler’ in namespace ‘::’ does not name a type
 sipwxWebViewArchiveHandler::sipwxWebViewArchiveHandler(const  ::wxWebViewArchiveHandler& a0):  ::wxWebViewArchiveHandler(a0), sipPySelf(0)
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~
```
followed by ~1600 more lines of error message.

However I *can* build with WebKitGTK+ 2.4.11 quite smoothly, and this version is a dependency of wxPython Phoenix on most common Linux distributions.

According to official WebKit [website](https://trac.webkit.org/wiki/WebKitGTK/WebKit2Roadmap), WebKitGTK+ 2.4 which uses WebKit1 API, has been deprecated since 2014. WebKitGTK+ developer Michael Catanzaro [states](https://lists.webkit.org/pipermail/webkit-gtk/2016-September/002779.html) "this ancient and insecure version of WebKit is no longer supported".

Since wxPython Phoenix is supposed to be a modern implementation of wxPython, it is reasonable that we should build on top of the modern version of WebKitGTK+, instead of relying on an unsupported version that's deprecated 3 years ago. Thanks!

**Comment by RobinD42** [comment]
The errors you reported are due to the wxWebKit classes being disabled in the wxWidgets build.  When you have a chance try again with a clean source tree and capture the build output when the wxWidgets configuration step is running.  There may be some information about why it is rejecting the new version of WebKitGTK.  

Either way, I expect that things have been changed already in wxWidgets on the master branch and that we'll get support for the newer library when 4.0 is done and we start on 4.1.

**Comment by haozhangphd** [comment]
Thank you for your reply. After some digging, I found out that webkit2gtk is indeed supported. However it needs to be explicated enabled during building by passing the `--gtk3` flag. The relevant code is in the `configure.in:7063` of wxWidgets, webkit2gtk will not be enabled unless GTK3 is used, which is not the default behavior. I may be wrong, but I don't think this behavior is documented.

So this is not a bug. But please do support webkit2gtk *as default* instead of webkit1gtk, as webkit1gtk is really abandoned and full of [security bugs](https://lists.webkit.org/pipermail/webkit-gtk/2016-August/002765.html).

**Comment by RobinD42** [comment]
Ok, good.

I have been planning on changing the default to --gtk3, just haven't gotten around to it yet.
