### ISSUE TITLE
Cannot build on 3.14

### ISSUE THREAD

**Issue by clin1234** [wxWidgets/Phoenix#2751]
running build_ext
      building 'wx.svg._nanosvg' extension
      creating build/wxsvg/temp.linux-x86_64-cpython-314t/wx/svg
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -O3 -fPIC -DNANOSVG_IMPLEMENTATION=1 -DNANOSVGRAST_IMPLEMENTATION=1 -DNANOSVG_ALL_COLOR_KEYWORDS=1 -Iext/nanosvg/src -I/home/cc/venv/include -I/usr/include/python3.14t -c wx/svg/_nanosvg.c -o build/wxsvg/temp.linux-x86_64-cpython-314t/wx/svg/_nanosvg.o
      wx/svg/_nanosvg.c:2455:80: error: unknown type name ‘__pyx_vectorcallfunc’; did you mean ‘vectorcallfunc’?
       2455 | static CYTHON_INLINE PyObject *__Pyx_PyVectorcall_FastCallDict(PyObject *func, __pyx_vectorcallfunc vc, PyObject *const *args, size_t nargs, PyObject *kw);
            |                                                                                ^~~~~~~~~~~~~~~~~~~~
            |                                                                                vectorcallfunc
      wx/svg/_nanosvg.c:25876:69: error: unknown type name ‘__pyx_vectorcallfunc’; did you mean ‘vectorcallfunc’?
      25876 | static PyObject *__Pyx_PyVectorcall_FastCallDict_kw(PyObject *func, __pyx_vectorcallfunc vc, PyObject *const *args, size_t nargs, PyObject *kw)
            |                                                                     ^~~~~~~~~~~~~~~~~~~~
            |                                                                     vectorcallfunc
      wx/svg/_nanosvg.c:25921:80: error: unknown type name ‘__pyx_vectorcallfunc’; did you mean ‘vectorcallfunc’?
      25921 | static CYTHON_INLINE PyObject *__Pyx_PyVectorcall_FastCallDict(PyObject *func, __pyx_vectorcallfunc vc, PyObject *const *args, size_t nargs, PyObject *kw)
            |                                                                                ^~~~~~~~~~~~~~~~~~~~
            |                                                                                vectorcallfunc
      wx/svg/_nanosvg.c: In function ‘__Pyx_CyFunction_CallAsMethod’:
      wx/svg/_nanosvg.c:26610:6: error: unknown type name ‘__pyx_vectorcallfunc’; did you mean ‘vectorcallfunc’?
      26610 |      __pyx_vectorcallfunc vc = __Pyx_CyFunction_func_vectorcall(cyfunc);
            |      ^~~~~~~~~~~~~~~~~~~~
            |      vectorcallfunc
      wx/svg/_nanosvg.c:2545:45: error: initialization of ‘int’ from ‘vectorcallfunc’ {aka ‘struct _object * (*)(struct _object *, struct _object * const*, long unsigned int,  struct _object *)’} makes integer from pointer without a cast [-Wint-conversion]
       2545 | #define __Pyx_CyFunction_func_vectorcall(f) (((PyCFunctionObject*)f)->vectorcall)
            |                                             ^
      wx/svg/_nanosvg.c:26610:32: note: in expansion of macro ‘__Pyx_CyFunction_func_vectorcall’
      26610 |      __pyx_vectorcallfunc vc = __Pyx_CyFunction_func_vectorcall(cyfunc);
            |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      wx/svg/_nanosvg.c:26613:16: error: implicit declaration of function ‘__Pyx_PyVectorcall_FastCallDict’; did you mean ‘__Pyx_PyObject_FastCallDict’? [-Wimplicit-function-declaration]
      26613 |         return __Pyx_PyVectorcall_FastCallDict(func, vc, &PyTuple_GET_ITEM(args, 0), (size_t)PyTuple_GET_SIZE(args), kw);
            |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            |                __Pyx_PyObject_FastCallDict
      wx/svg/_nanosvg.c:26613:16: error: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
      26613 |         return __Pyx_PyVectorcall_FastCallDict(func, vc, &PyTuple_GET_ITEM(args, 0), (size_t)PyTuple_GET_SIZE(args), kw);
            |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      error: command '/opt/gcc-latest/bin/gcc' failed with exit code 1
      Command '/home/cc/venv/bin/python3.14t setup-wxsvg.py build_ext --inplace' failed with exit code 1.
      Finished command: build_others (0m1.247s)
      Finished command: build_py (7m31.954s)
      Finished command: build (12m44.884s)
      WARNING: Building this way assumes that all generated files have been
      generated already.  If that is not the case then use build.py directly
      to generate the source and perform the build stage.  You can use
      --skip-build with the bdist_* or install commands to avoid this
      message and the wxWidgets and Phoenix build steps in the future.
      
      "/home/cc/venv/bin/python3.14t" -u build.py build
      Command '"/home/cc/venv/bin/python3.14t" -u build.py build' failed with exit code 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wxPython
Failed to build wxPython
ERROR: Failed to build installable wheels for some pyproject.toml based projects (wxPython)

**Comment by echoix** [comment]
Just to be sure, with your current setup and the steps you used, would you be able to create it for an older Python version that we successfully build wheels for? (You need to be sure wheels aren't used).

Also, I see that it is the free-threaded version of the 3.14 beta release you are using. Since free threaded was optionally available since 3.13, if you're able with 3.13, does 3.13t work too?



Some work can be done for improving the experience with the cython module. For example, the practice of including/committing .c outputs isn't recommended as improvements happened since the old days of Python packaging.

If you feel adventurous, in a source distribution, I would have removed the Python-generated .c files if I suspected they would be outdated, and let cython use the .pyx files directly.

**Comment by echoix** [comment]
Note that you didn't follow the bug report template, and didn't provide any other context, apart from a dump of (unformatted) console text, so we can't help you very much more than this.
