### ISSUE TITLE
SIP 4.18 build problems - vscroll multiple inheritance ambiguity

### ISSUE THREAD

**Issue by swt2c** [wxWidgets/Phoenix#82]
Phoenix doesn't build with SIP 4.18.  It seems that SIP changed the way that it generates its type cast functions (in the case of multiple inheritance), resulting in compile errors:

```
[185/720] cxx: sip/cpp/sip_corewxHeaderButtonParams.cpp -> build/waf/2.7/sip/cpp/sip_corewxHeaderButtonParams.cpp.3.o
../../../sip/cpp/sip_corewxHVScrolledWindow.cpp: In function 'void* cast_wxHVScrolledWindow(void*, const sipTypeDef*)':
../../../sip/cpp/sip_corewxHVScrolledWindow.cpp:2900:59: error: 'wxVarScrollHelperBase' is an ambiguous base of 'wxHVScrolledWindow'
         return static_cast<wxVarScrollHelperBase *>(sipCpp);
                                                           ^
../../../sip/cpp/sip_corewxHVScrolledWindow.cpp:2906:59: error: 'wxVarScrollHelperBase' is an ambiguous base of 'wxHVScrolledWindow'
         return static_cast<wxVarScrollHelperBase *>(sipCpp);
                                                           ^
```

The problem seems like it could be avoided in SIP itself (by checking for duplicate base types), but other than that, I don't see a way around it other than editing the generated SIP code.  I'll prepare a patch to do that for now.  (I had originally thought this was a GCC 6.1.1 problem, but I failed to notice that SIP had changed too.)

**Comment by swt2c** [comment]
SIP 4.18 build fixed by #99 and #100.

**Comment by RobinD42** [comment]
It may still have something to do with the version of GCC as I'm not seeing these issues on my dev machines.  It looks like there was a commit to SIP yesterday that may be addressing at least part of this issue. (https://www.riverbankcomputing.com/hg/sip/rev/91206af66161)  I'll update to that version of sip (probably later today) and then you can check again and see if maybe the fixes can be adjusted too.  I don't mind the stc changes in #99, but I really do not want to have to patch code generated by sip like what is in #100.

**Comment by swt2c** [comment]
Yes, the SIP patch was from me, he didn't give me credit.  :-P

So yeah, once the next version of SIP is released, or you use the latest from hg, #100 won't be needed.

**Comment by RobinD42** [comment]
Oops, I guess I never finished my update to 4.18 a few weeks ago like I thought I did.  No wonder I was seeing different results than you!  Anyway, changes for using the 4.18.1 snapshot will be landing soon.

**Comment by RobinD42** [comment]
Builds with the new sip are done
