### ISSUE TITLE
wxPython 4.2.1 does not compile with GCC 14

### ISSUE THREAD

**Issue by qookei** [wxWidgets/Phoenix#2493]
**Operating system**: Gentoo Linux
**wxPython version & source**: Distro wxPython 4.2.1
**Python version & source**: Distro Python 3.11

**Description of the problem**:

GCC 14 makes `-Wincompatible-pointer-types` ([among others](https://inbox.sourceware.org/gcc/87ttp3tek1.fsf@oldenburg.str.redhat.com/)) error out by default, so the build fails with the following error:
```
[  9/929] Compiling sip/siplib/siplib.c
16:38:17 runner ['x86_64-pc-linux-gnu-gcc', '-UNDEBUG', '-pthread', '-O3', '-O3', '-march=znver2', '-pipe', '-ggdb3', '-pthread', '-fPIC', '-pthread', '-pthread', '-I/usr/include/gtk-3.0', '-I/usr/include/pango-1.0', '-I/usr/include/glib-2.
0', '-I/usr/lib64/glib-2.0/include', '-I/usr/lib64/libffi/include', '-I/usr/include/harfbuzz', '-I/usr/include/freetype2', '-I/usr/include/libmount', '-I/usr/include/blkid', '-I/usr/include/fribidi', '-I/usr/include/cairo', '-I/usr/include/
libpng16', '-I/usr/include/pixman-1', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/gio-unix-2.0', '-I/usr/include/atk-1.0', '-I/usr/include/at-spi2-atk/2.0', '-I/usr/include/at-spi-2.0', '-I/usr/include/dbus-1.0', '-I/usr/lib64/dbus-1.0
/include', '-pthread', '-UNDEBUG', '-g', '-I/usr/lib64/wx/include/gtk3-unicode-3.2-gtk3', '-I/usr/include/wx-3.2-gtk3', '-Isip/siplib', '-I../../../../sip/siplib', '-Iwx/include', '-I../../../../wx/include', '-Isrc', '-I../../../../src', '-
I/usr/include/python3.11', '-DPYTHONDIR="/usr/local/lib/python3.11/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python3.11/site-packages"', '-DHAVE_PYEXT=1', '-DHAVE_PYTHON_H=1', '-DHAVE_WX=1', '-DHAVE_WXADV=1', '-DHAVE_WXSTC=1', '-DHA
VE_WXHTML=1', '-DHAVE_WXGL=1', '-DHAVE_WXXML=1', '-DHAVE_WXXRC=1', '-DHAVE_WXRICHTEXT=1', '-DHAVE_WXMEDIA=1', '-DHAVE_WXRIBBON=1', '-DHAVE_WXPROPGRID=1', '-DHAVE_WXAUI=1', '-D_FILE_OFFSET_BITS=64', '-DWXUSINGDLL', '-D__WXGTK__', '../../../.
./sip/siplib/siplib.c', '-c', '-o/var/tmp/portage/dev-python/wxpython-4.2.1/work/wxPython-4.2.1-python3_11/build/waf/3.11/gtk3/sip/siplib/siplib.c.1.o', '-DNDEBUG', '-DNDEBUG']
../../../../sip/siplib/siplib.c: In function ‘parsePass1’:
../../../../sip/siplib/siplib.c:3905:20: error: assignment to ‘sipSimpleWrapper *’ {aka ‘struct _sipSimpleWrapper *’} from incompatible pointer type ‘PyObject *’ {aka ‘struct _object *’} [-Wincompatible-pointer-types]
 3905 |             *selfp = va_arg(va, PyObject *);
      |                    ^

```

**Comment by qookei** [comment]
Hmm, this actually seems to be a bug in SIP itself.

**Comment by swt2c** [comment]
Yes, I reported it to SIP upstream.

**Comment by swt2c** [comment]
Fixed in sip (not yet released): https://www.riverbankcomputing.com/hg/sip/rev/afc99fa84d0d

**Comment by qookei** [comment]
Thanks for reporting it upstream! Closing as wxPython compiles fine with SIP 6.8.1.

**Comment by tfmoraes** [comment]
I'm trying to install from pypi using pip in Fedora 40 (GCC 14) and having this issue. Is it possible to force run sip when using `pip install`?

**Comment by swt2c** [comment]
> I'm trying to install from pypi using pip in Fedora 40 (GCC 14) and having this issue. Is it possible to force run sip when using `pip install`?

On Fedora 40, you can just install wxPython with `dnf install python3-wxpython4` and not have to compile it yourself...

**Comment by tfmoraes** [comment]
I know. But the same problem will happen in other linux distro with gcc14 and without wxpython package.

**Comment by mixmid** [comment]
This patch has helped me.

[gcc_14.zip](https://github.com/user-attachments/files/16254293/gcc_14.zip)

But i will be appreciated if someone tells how to patch source files before compilation in a python way, i.e. to download wxPython-4.2.1.tar.gz, unpack, then patch, after build by 

$ pip install wxPython
