### ISSUE TITLE
Can not build:  no member named 'FromSVG' in 'wxBitmapBundle' 

### ISSUE THREAD

**Issue by lbartoletti** [wxWidgets/Phoenix#2253]
**Operating system**: FreBSD
**wxPython version & source**:         3.2.0 release / wxWidgets 3.2.0
**Python version & source**:           3.9

**Description of the problem**:

I'm trying to update wxPython ports (package) on FreeBSD using the wxWidgets 3.2.0 version.

wxPython 4.2.0 can not build with wxWidgets 3.2.0

```shell
../../../../sip/cpp/sip_corewxBitmapBundle.cpp:826:63: error: no member named 'FromSVG' in 'wxBitmapBundle'
            sipRes = new  ::wxBitmapBundle( ::wxBitmapBundle::FromSVG(data,*sizeDef));
                                            ~~~~~~~~~~~~~~~~~~^
../../../../sip/cpp/sip_corewxBitmapBundle.cpp:870:63: error: no member named 'FromSVGFile' in 'wxBitmapBundle'
            sipRes = new  ::wxBitmapBundle( ::wxBitmapBundle::FromSVGFile(*path,*sizeDef));
                                            ~~~~~~~~~~~~~~~~~~^
../../../../sip/cpp/sip_corewxBitmapBundle.cpp:916:63: error: no member named 'FromSVGResource' in 'wxBitmapBundle'
            sipRes = new  ::wxBitmapBundle( ::wxBitmapBundle::FromSVGResource(*name,*sizeDef));
                                            ~~~~~~~~~~~~~~~~~~^
3 errors generated.

Waf: Leaving directory `/wrkdirs/usr/ports/x11-toolkits/py-wxPython4/work-py39/wxPython-4.2.0/build/waf/3.9/gtk3'
Build failed
 -> task in '_core' failed with exit status 1 (run with -v to display more information)
Command '"/usr/local/bin/python3.9" /wrkdirs/usr/ports/x11-toolkits/py-wxPython4/work-py39/wxPython-4.2.0/bin/waf-2.0.24 --wx_config=/usr/local/bin/wxgtk3u-3.2-config --gtk3 --python="/usr/local/bin/python3.9" --out=build/waf/3.9/gtk3 configure build ' failed with exit code 1.
```

For information, wxWidgets is built with nanosvg

**Comment by swt2c** [comment]
Are you 100% sure that wxWidgets was build with nanosvg?  Can you supply the full build logs for wxWidgets (are you using it unbundled?) and wxPython?

**Comment by rhurlin** [comment]
> Are you 100% sure that wxWidgets was build with nanosvg? 

Probably the suspicion is correct that the coming port wxgtk32 is not configured correctly for nanosvg under FreeBSD.

Anyway, I have similar problems when using wxgtk32 to build a future version 8.4 of [SAGA GIS](https://sourceforge.net/p/saga-gis/code/ci/master/tree/saga-gis/) on FreeBSD. After some trial and error it turned out that `--with-nanosvg` is not used correctly for gmake, see [FreeBSD Bugzilla – Bug 265093](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=265093#c25). A small change in the FreeBSD port makes it possible to use the _internal_ nanosvg, so the SAGA GIS builds and works correctly.

**Comment by rhurlin** [comment]
In the meantime I was able to successfully build wxPython 4.2.0 on FreeBSD, after installing the patched version of wxgtk32, see my last posting.

**Comment by lbartoletti** [comment]
I confirm! Thanks @rhurlin 

Sorry for the noise @swt2c
